### ISSUE TITLE
I still don't trust you

### ISSUE THREAD

**Issue by Rainb0wCodes** [codecat/go-enet#3]
I still don't trust you! Your repo only has thirteen (13) GitHub stars. I have read the source code and this is clearly a decoy module where the actual code is written in C. Because this is written in C, I am forced to believe this is malware. I am going to report your code to GitHub.

**Comment by codecat** [comment]
There is no malware in the `enet.lib` included in the repository. Virustotal report: https://www.virustotal.com/gui/file/2b9e85e889894b316a183ff6ac6f3ef16335f86bb9c00fb1cef5c50ae2b67647

If you want, you can even replace it with your own. On Linux, it will use the system-installed library.

**Comment by Rainb0wCodes** [comment]
I know but your code is written in C and C = malware

**Comment by Rainb0wCodes** [comment]
I hate C

**Comment by Rainb0wCodes** [comment]
cgo should be deleted from Go

**Comment by warent** [comment]
This is the most bizarre issue I've ever seen on Github. Unsure if this is a bizarre joke, troll, or if the commenter is a literal child, lol...
