### ISSUE TITLE
Socks5 support

### ISSUE THREAD

**Issue by DevilLord41** [codecat/go-enet#8]
Is there socks5 support for this?

**Comment by codecat** [comment]
Not specifically. I'm not sure if enet itself does socks proxies.

**Comment by DevilLord41** [comment]
I have enet in C++ support for socks, but not sure how it would works in Go

**Comment by codecat** [comment]
This would probably have to be implemented into Enet itself (the C library). Will close for now as it's kind of out of scope for this project.
